version: '3.8'

services:
  # Service 1: NATS Server (Message Broker)
  nats:
    image: nats:latest
    container_name: nats_server
    ports:
      - "4222:4222" # Port utama komunikasi aplikasi
      - "8222:8222" # Port monitoring dashboard
    command: "-js"
    restart: always